version: '3'
services:
  frontend:
    image: mjorkk/ni_imena:backend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: mjorkk/ni_imena:frontend
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3001:3001"


