name: Docker Build and Push

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKER_IMAGE_FRONTEND: ${{ secrets.DOCKERHUB_IMAGE_FRONTEND }}
  DOCKER_IMAGE_BACKEND: ${{ secrets.DOCKERHUB_IMAGE_BACKEND }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker-compose build
          docker push $DOCKER_IMAGE_FRONTEND
          docker push $DOCKER_IMAGE_BACKEND
      - name: Send webhook notification
        uses: joelwmale/webhook-action@2.3.2
        with:
          url: http://20.126.63.144:1337/log-github-webhook
          method: POST
          body: '{"message": "Docker image has been built and pushed."}'
